@PAELoginAPI_HostAddress = http://localhost:5010

GET {{PAELoginAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{PAELoginAPI_HostAddress}}/api/users
Content-Type: application/json

{
  "name":"Administrador",
  "email":"admin@gmail.com",
  "password":"admin123"
}

###

POST {{PAELoginAPI_HostAddress}}/api/users
Content-Type: application/json

{
  //User
}

###

GET {{PAELoginAPI_HostAddress}}/api/users/login/string/string

###
